### ISSUE TITLE
cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo behaves like full debug build (12 FPS)

### ISSUE THREAD

**Issue by hellrazor4223** [OpenXcom/OpenXcom#1284]
After latest changes in cmake compilation the cmake configuration option:
cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo behaves like a full Debug build. Meaning this is unplayable with 12 FPS or so.
Please make sure to revisit changed procedures and make -DCMAKE_BUILD_TYPE=RelWithDebInfo
Playable again :)

**Comment by R1dO** [comment]
Upon further investigation it could easily be that there is some old definition in your CMAKE cache causing the build to fail.

The linked fix might not even help. The only reason it worked on my end is because i removed the complete (cmake) build directory (which contains the cache). 

Could you please try to delete your current build directory and try again (e.g. configure cmake and compile afterwards). Please share the results before we integrate the linked PR.

**Comment by hellrazor4223** [comment]
I already deleted the build directory and made a completely new configuration. Behaviour stays the same. Sorry for my sloppy bugs reports (as usual).

**Comment by R1dO** [comment]
No need to be sorry, i've seen worse ;)

Before pestering supsuper to give the go on a PR, could you be so kind as to attach [1] the `CMakeCache.txt` file (should be in the root of your build directory). So i can have a (basic) look if the PR has any chance of resolving your issue [2].

[1] Or send it to me via discord PM, since it contains absolute paths with your username and other unique identifiers.
[2] Or you could try bringing in the PR branch, activate it, check if it works and report back.

**Comment by hellrazor4223** [comment]
[CMakeCache.txt](https://github.com/OpenXcom/OpenXcom/files/5531577/CMakeCache.txt)
Here you go thats made with cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo in a fresh clone of github OpenXcom Repo.

**Comment by hellrazor4223** [comment]
Problem does not show up anymore with https://github.com/OpenXcom/OpenXcom/commit/70b86aff54f9cd86450b56f6272d9fdf66edb276
But is recreateable with: 
https://github.com/OpenXcom/OpenXcom/commit/7aae3f45365d4636b40e05ac80f6ebd2575efb59

Probably the missing Doxygensettings?

**Comment by R1dO** [comment]
That is weird, between those two commits there is no indication of any code change touching the build setup.

Is it possible you did anything else in the meanwhile? 
Or perhaps a system update touching the compiler chain?

**Comment by hellrazor4223** [comment]
No nothing in that regard.

**Comment by R1dO** [comment]
Well in that case i'm officially out of options.
- Your CMakeCache did seem not reveal anything of interest.
- The problem seem to have solved itself on your side

The only thing left (from my perspective) is to keep monitoring this in case the problem resurfaces.
In the meanwhile i will retract the linked PR (it is not a solution for this problem making the commit message misleading).

**Comment by uqs** [comment]
So sorry to hear about that. If you can still repro at head, a verbose build log could potentially also help.

I cannot repro, sadly:

```
cmake -B build-reldeb -DCMAKE_BUILD_TYPE=RelWithDebInfo . 
...
cmake --build build-reldeb -v 
...
[  0%] Building CXX object src/CMakeFiles/openxcom.dir/lodepng.cpp.o
cd /home/uqs/games/OpenXcom/build-reldeb/src && /usr/bin/c++ -DDATADIR=\"/usr/local/share/openxcom/\" -DGIT_BUILD=1 -I/home/uqs/games/OpenXcom/build-reldeb -isystem /usr/local/include/SDL -isystem /usr/local/include -isystem /usr/local/include/.. -O2 -g -DNDEBUG -Wno-unused-function -std=c++11 -o CMakeFiles/openxcom.dir/lodepng.cpp.o -c /home/uqs/games/OpenXcom/src/lodepng.cpp
```

It has -O2 -g. You should also grep for CXX_FLAGS and provide that output. For me it's:

```
 % grep -r 'CXX_FLAGS.*=' build-reldeb
build-reldeb/src/CMakeFiles/openxcom.dir/flags.make:CXX_FLAGS = -O2 -g -DNDEBUG -Wno-unused-function -std=c++11
build-reldeb/CMakeCache.txt:CMAKE_CXX_FLAGS:STRING=
build-reldeb/CMakeCache.txt:CMAKE_CXX_FLAGS_DEBUG:STRING=-g
build-reldeb/CMakeCache.txt:CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
build-reldeb/CMakeCache.txt:CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
build-reldeb/CMakeCache.txt:CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
build-reldeb/CMakeCache.txt:CMAKE_CXX_FLAGS-ADVANCED:INTERNAL=1
build-reldeb/CMakeCache.txt:CMAKE_CXX_FLAGS_DEBUG-ADVANCED:INTERNAL=1
build-reldeb/CMakeCache.txt:CMAKE_CXX_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
build-reldeb/CMakeCache.txt:CMAKE_CXX_FLAGS_RELEASE-ADVANCED:INTERNAL=1
build-reldeb/CMakeCache.txt:CMAKE_CXX_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1
```

**Comment by MeridianOXC** [comment]
Closing as obsolete.
Please retest and make a new report if needed.
