### ISSUE TITLE
Aliens can shoot through the front of the Avenger

### ISSUE THREAD

**Issue by MarkusRamikin** [OpenXcom/OpenXcom#1312]
https://openxcom.org/forum/index.php/topic,9503.msg137147.html#msg137147

I hope this isn't a "feature"...

[savegame - shooting through avenger.zip](https://github.com/OpenXcom/OpenXcom/files/6095519/savegame.-.shooting.through.avenger.zip)

To see this in action just load this save and "End Turn".

**Comment by MeridianOXC** [comment]
OpenXcom engine works correctly (as explained in the forum post).

The issue can be fixed by changing the Avenger map by a mod... but that's a suggestion for modders, OXC/E devs won't do that. We tend to keep our fingers away from any original data files and their derivatives. Or at least from including them in the OpenXcom package.

**Comment by MeridianOXC** [comment]
Closing as explained.
