### ISSUE TITLE
mission tried to find a waypoint in zone 5 but this region only has zones valid up to 0

### ISSUE THREAD

**Issue by mauirixxx** [OpenXcom/OpenXcom#1323]
[oxc - mod causing crash.zip](https://github.com/OpenXcom/OpenXcom/files/6251751/oxc.-.mod.causing.crash.zip)

Step to reproduce: let the timer run to 1:59:55 in the attached save file. I know it has something to do with my cities in Hawaii mod but I can't seem to track down where I went wrong with it, as they work fine until the retaliation mission.

**Comment by MeridianOXC** [comment]
You have overridden (read: deleted) the necessary mission zones in the region STR_PACIFIC. Game crashes, because it can't find them.

Also, please, this is a place to report OpenXcom bugs, not custom mod bugs.
You can get help with modding issues on the OpenXcom forum, or in the OpenXcom discord server.

Closing issue as irrelevant.
