### ISSUE TITLE
Large units are "piling up" at one position during terror missions.

### ISSUE THREAD

**Issue by TCH68k** [OpenXcom/OpenXcom#1403]
As the title said: whenever i start a terror mission with aliens who uses large - as in: 2x2 sized - terror units, they get grouped at the same point. (Well, maybe one or two is placed elsewhere, but not necessarily.)
`difficultyDemigod` is set to `true` in the `/usr/local/share/openxcom/standard/xcom1/difficulty.rul` file.
It is the latest version: 20230205 and i did not experienced this with the last version i used (20220816).

Savegames:
http://oscomp.hu/depot/CYBERDISK_ORGY.sav
http://oscomp.hu/depot/REAPER_ORGY.sav
http://oscomp.hu/depot/SECTOPOD_ORGY.sav

**Comment by Warboy1982** [comment]
if you're using demigod mode, try reversing the order of the units in the terror mission deployment (ie: so the large units spawn first), you'll get a much more even distribution.

**Comment by Warboy1982** [comment]
added an "official" demigod mod and adjusted the behaviour a little.


good luck.

**Comment by TCH68k** [comment]
Thanks, it fixed the terror missions.

I gave the new mod a test run with all the types of missions where large units are present and it seems, that terror ship and battleship missions are also somewhat affected by this uneven distribution, but only in farm environment and only if those of little houses are present:

http://oscomp.hu/depot/FARM_STOCK.sav

This is more likely will happen with terror ships, because battleships occupies so much terrain already that not really much houses will spawn. But sometimes it happens.

In all other cases (terror or battleship in a non-farm environment, terror mission, base defence, alien base assault and Cydonia) it works perfectly. Thank you.

**Comment by Warboy1982** [comment]
i'll take sometimes over every time ;)
in testing it seemed like a much better distribution, but of course the actual generation of the map would influence that
when i got maps with only one map block capable of supporting large units they still clustered together, but it was three clusters instead of one, i guess i could expand it to other missions too, but like i said, it depends mostly on the map generation at this point, not so much the spawn order. i feel like this sorts out 90% of cases of pile-ups, there's not much i can do for terror ships and battle ships, as you pointed out. 
i'd call this a "good enough" fix.

**Comment by TCH68k** [comment]
Sure, this is way good enough. :)
Not just because only "farm-environmented" terror ship and battleship missions are affected, but this way the "piles" are only a maximum of 3 units out of the present 8-10 and not all of them in one big group, which is absolutely acceptable; sometimes we can see 3 Cyberdisks/Reapers/Sectopods together under normal circumstances too (base assaults, alien bases, whatever).
So, yeah, definitely fair enough.
