### ISSUE TITLE
Psi Capture does not work with Sectopods?

### ISSUE THREAD

**Issue by TCH68k** [OpenXcom/OpenXcom#1404]
I play with Psi Capture turned on and it works. However, today i've ran into that there was only one Sectopod left in the battlescape and if i did MC on it and ended the turn, the game continued. I thought there is another Ethereal or Sectopod around there and i wondered why does it not act, why does it not shoots civilians, or try to do a psi attack on my crew...

Since i could not kill the last Sectopod with my Hovertank (i killed all of the other Sectopods with each other - they wield a laser weapon, so they are vulnerable to their own weapon), i moved it to the Avanger and killed it with laser rifles. And then the game ended. Then i realized, that the Psi Capture did not work with that last Sectopod.

Savegame:
http://oscomp.hu/depot/MOSTMIVAN.sav

MC the Sectopod, don't kill it, end the turn. The game will continue.

It is the latest git version: 20230210.

**Comment by MeridianOXC** [comment]
Yes, this is by design.

Sectopods and Cyberdiscs cannot be captured alive.

"capturable: false" in units.rul

**Comment by TCH68k** [comment]
Strange decision. I know that "officially" they cannot be captured, but:
1. Actually they can be; i've captured several of them in the original game via Stun Bomb or a non fatal hit, because they indeed can be stunned, even if it is not logical.
2. Psi Capture was not available in the original game, so if OpenXCom already diverted from the original in that aspect, then why did not in this? Also, if OpenXCom "supersedes" the original game by not allowing robotic units to be stunned, then i say, that's actually logical, but if i took control over it, then why cannot i command it to walk into the Alien Containment?

Anyways, since the game is moddable, this is no problem. Thank you for the answer.

**Comment by MeridianOXC** [comment]
Because another guy reporting here in 2018 said that they cannot be captured in the original game: https://github.com/OpenXcom/OpenXcom/pull/1187

Quoting: "It is definitely not possible in vanilla X-COM to capture a live Cyberdisc or Sectopod. This is confirmed not only by my own experience but also by these excerpts from the UFOpaedia website: The two robotic units (Sectopods and Cyberdiscs) cannot be captured alive. Therefore, only 27 of the race/rank combos can be kept in a containment facility. The two robotic units (Sectopods and Cyberdiscs) cannot be captured alive or studied directly; there isn't even a RESEARCH.DAT entry for them."

**Comment by Player701** [comment]
Hey there, I'm that "another guy" in question.

We all know the original game has lots of bugs, so I guess it might be possible for normally non-capturable live specimens to appear due to data corruption. I never encountered any while playing the CE version, although I did also use Seb76's [UFO Extender](https://www.ufopaedia.org/index.php/UFOextender) for (mostly) glitch-free playthroughs and QoL features. However, according to [RESEARCH.DAT](https://www.ufopaedia.org/index.php/RESEARCH.DAT), there are no research topics for Sectopod or Cyberdisc, so even if one were to be captured somehow, it'd be impossible to interrogate it. And while these units _can_ be downed by stun bombs, they never get up and are considered dead for all intents and purposes.

**Comment by TCH68k** [comment]
Now, that is interesting. I remember capturing and researching them. Granted, this was in the Amiga OCS and Amiga AGA versions, not the MS-DOS one, so maybe this is a version difference and under the MS-DOS version they are not researchable. There is a savegame editor for the Amiga versions (http://oscomp.hu/?lang/en*details/UfoED_Amiga_109) which IIRC also allows to add alive specimens of robotic units to the Alien Containment. (This was the program which made me aware, that there are hidden stuff such as Alien Reproduction (which can be researched) and Alien Habitat (which cannot).)

**Comment by Player701** [comment]
It is possible to add any species/rank combination to the Alien Containment even in the DOS version, see [ASTORE.DAT](https://www.ufopaedia.org/index.php/ASTORE.DAT); but you can only interrogate them if RESEARCH.DAT has a corresponding research topic entry.

**Comment by TCH68k** [comment]
Which means, the RESEARCH.DAT contains entries for them on Amiga. Dunno why though.

**Comment by MeridianOXC** [comment]
Can you upload the RESEARCH.DAT file from your Amiga installation?

**Comment by TCH68k** [comment]
The AGA version's RESEARCH.DAT is here: http://oscomp.hu/depot/amiga_aga_research.dat
I did not find the OCS version's one. It must be in some kind of package or the binaries itself. The string of "RESEARCH.DAT" is present in both the Geo and Tactical binaries and savegames, but i did not find it anywhere.
You can get both version (both in floppy and installed setup) from these links though to investigate:
http://oscomp.hu/?details/Ufo:_Enemy_Unknown_A500_disks_Amiga_81
http://oscomp.hu/?details/Ufo:_Enemy_Unknown_A500_HD_Amiga_82
http://oscomp.hu/?details/Ufo:_Enemy_Unknown_AGA_disks_Amiga_84
http://oscomp.hu/?details/Ufo:_Enemy_Unknown_AGA_HD_Amiga_85

**Comment by MeridianOXC** [comment]
Thank you.
I'll have a look at it over the weekend.
